### ISSUE TITLE
Serial control

### ISSUE THREAD

**Issue by willfromlondon** [schoolpost/CinePI#14]
This project has been incredible for some projects I've been working on. I'd love to be able to control basic settings (ISO/white balance/framerate/tint) from an arduino through the serial port - Is this something that's possible on this 1.0.1 release?

**Comment by schoolpost** [comment]
> This project has been incredible for some projects I've been working on. I'd love to be able to control basic settings (ISO/white balance/framerate/tint) from an arduino through the serial port - Is this something that's possible on this 1.0.1 release?

This could be possible addition in the future yes, for consistency it would likely re-use the existing Blackmagic Camera Control protocol ( https://documents.blackmagicdesign.com/DeveloperManuals/BlackmagicCameraControl.pdf ) unless a better alternative is suggested.

**Comment by casparmkerr** [comment]
I just discovered this amazing project, and I think physical control (ie through serial because of the lack of analog GPIO and i2c being used by the camera) would be a killer feature for making CinePi useful for less controlled environments! 

I haven't ordered the necessary hardware yet as some further development seems to be needed to make the project useful "out of the box", and without the source code easily available (in addition to me really only having casual experience with python and java - no lower level code), I am not sure if I can really contribute much. That said, I'd be happy to give it a go if you found a practical way to share the source and not just builds!

**Comment by willfromlondon** [comment]
Is recording in log format possible? The colour of the sensor is great but it would be awesome to get some more dynamic range.

**Comment by Tiramisioux** [comment]
@casparmkerr Extra I2C can be achieved by assigning a new channel to two GPIO Pins

https://medium.com/cemac/creating-multiple-i2c-ports-on-a-raspberry-pi-e31ce72a3eb2

Working on a prototype for a CinePi HAT with physical controls - ISO, shutter angle, fps and manual speed ramping. 

Doing some final tests now and will try to compile building instructions and code. But basically it is achieved by potentiometers > ADC converter > GPIO 26 (as SDA) and 5 (as SCL) > I2C > Raspberry Pi > Python script exectuting shell commands > v4l2-ctl settings.

The Python-script runs in parallell with the CinePi system so there is no change to the CinePi code itself.

Code can be found here: https://github.com/Tiramisioux/CineMate-HAT

It is not so pretty and much work in progress but all functionality is there. Now working on making it robust and more elegant and easy to follow.

Went down the HAT route for making a compact and sturdy solution, but the same thing could easily be achieved with a microcontroller and USB. First ideas I tried out was attaching a Microbit :) to the Pi for manual controls, sending data though USB to a Python script on the Pi executing shell commands.

**Comment by Tiramisioux** [comment]
Is it possible to manipulate the basic Black Magic / Bluetooth Camera Control settings via the command line?

I have managed to control the v4l2-ctl settings directly using hardware peripherals (potentiometers etc) but I think a more elegant solution would be to reach them the same way the CinePi-system does.
