### ISSUE TITLE
Limited record time + weird files

### ISSUE THREAD

**Issue by pu3lkah** [schoolpost/CinePI#4]
Hi, so i have now been using your program for a few weeks on my raspberry/super 8 hybrid, and i love it. Apart from the bluetooth control on android I've already reported, i've ran into two other issues. The main one being that i cannot record more than approximately 40 seconds of video, and the more I record the shorter my record time get. At first i was using a cheap pny ssd, and I thought it might be that the drive wasn't fast enough. So I switched to a 500go samsung t7, which should be even faster than what the pi can output through usb 3 (i'm using a rpi 4b 4go ram), but i'm still running into the same issue. Both disks were formatted to exfat, I don't know if it comes from the disk or the board, if it should have more ram or if overclocking it a bit more might help. (I don't know if you ever ran into a similar issue, since in your video you're saying that you also are using a 4gb version)
The second one, which is not a big issue for me but i thought it might be worth letting you know, is that the files i record show as weird black images with color lines as if every file were corrupted (see screenshots) and it says that the image size is 128*67px. Also I cannont open it in premiere pro (it says "file not supported or damaged". But, where it get really weird, (but also the reason why I'm saying it's not a big issue) is that I can open the files in camera raw, and there i have all of my dng files, full size, perfectly fine, that i can then export in jpegs or png frame sequence. I have no idea what might be causing it, and i already tried re-flashing the sd card on the pi.
Thank you for your time and keep up the great work, it helped me tremendously in my projects ! I wish i could help with those issue, unfortunately i don't know much about programming. Hope those reports can help you fixing as many issues as you can in the future, and if i can do any tests for you than could be any help, let me know.
![Capture 1](https://user-images.githubusercontent.com/43523295/115904206-cee91a00-a464-11eb-829b-8dde1a2f8c03.JPG)
![Capture 2](https://user-images.githubusercontent.com/43523295/115904216-d14b7400-a464-11eb-8ea6-aa55cf108114.JPG)
![Capture 3](https://user-images.githubusercontent.com/43523295/115904231-d4defb00-a464-11eb-9326-84ba3dbee12f.JPG)

**Comment by schoolpost** [comment]
Really glad you've found the project useful. If you have any footage you are willing to share, please do. Love to see how it's being used. You can post it on the raspberry pi forums if you are a member there: https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=296776

To address your points, they are also issues I've faced myself. 

The limited record time is the biggest hurdle because It's very complicated and a fix isn't exactly trivial. Yes a Fast SSD helps and I've tried many ( CFAST to USB3 adapter, Samsung T5 SSD, NVME to USB 3.0 adapter ) but these don't seem to be the actual bottleneck. It really comes down to how frames are being written to disk, which right now happens through write caching in RAM. That is why you have ~40seconds of record time ( 4GB model ) while for myself I have used the 8GB model and consitently get ~90seconds. So basically It seems the writing of the frames to disk is still not efficient enough, because as soon as the RAM get's full and it has to write to disk directly it is not fast enough. Not exactly sure how this can be addressed, but I'll be investigating asking around to see how it can be fixed. 

The weird colored thumbnails is actually to be expected. Basically while this was in Alpha and especially while the Limited record time issue exists I didn't want to add any extra latency to writing a frame so I create an "empty thumbnail" so that is why it is kind of random. This is can be fixed with relative ease. But not looking to implement till the other issues are not solved.

**Comment by schoolpost** [comment]
>  The main one being that i cannot record more than approximately 40 seconds of video, and the more I record the shorter my record time get. 

May have solution soon, will keep you updated.

**Comment by pu3lkah** [comment]
Thanks for all the updates, I actually tried formatting the disk in ext4, and I have much better record time. I haven't tested extensively yet, so I don't know what is the exact time limit, but with a samsung t7 in ext4, i was able to record clips up to 2 minutes. Probably would be able to record a bit more, haven't tried recording to its limits yet.

**Comment by Tiramisioux** [comment]
Hi! Tried out the Samsung T7 500 MB drive in ext4 and was able to record a 24 minute clip @ 25 fps on a Raspberry Pi 4 with 8GB RAM. :)

**Comment by pu3lkah** [comment]
Nice to know it can be pushed so far ! Personally few minutes of clips at a time is fine by me. (Oh and I have the 4gb version so i probably wouldn't be able to record such long clips, I should test and see what the limitations are)

**Comment by Tiramisioux** [comment]
I agree, a couple of minutes is enough. :) But recording now seems stable and consistent, which is a huge step forward!
